### ISSUE TITLE
Copy and paste into feedback gives large error message

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#2992]
**Describe the bug**
Copy and paste from another resource (https://pl2.andrew.cmu.edu/PL2/Lesson?moduleId=5) with bullet points breaks the page and gives an error (see below) when pasting into feedback box. Not an issue when list is built in-platform

**To Reproduce**
1. Go to MCQ
2. Go to feedback
3. Paste bulleted list from a quote box into correct answer feedback box
4. error message

**Full error message**
Error: Cannot get the start point in the node at path [1] because it has no start text node. at Object.point (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:214648:15) at Object.start (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:215036:19) at Object.range (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:214960:24) at _loop (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:231650:24) at useChildren (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:231688:5) at Children (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:232032:212) at Le (https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:100:3) at Pj (https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:231:183) at di (https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:168:305) at Nj (https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js:168:236)
at Children (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:232032:212) at div at Editable$1 (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:232040:5) at Slate (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:235121:5) at https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243127:111 at ErrorBoundary (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:230625:5) at div at RichTextEditor (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243211:23) at RichTextEditorConnected (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243228:53) at Content (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:223716:20) at div at div at CardComponent (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:223706:26) at FeedbackCard (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243494:25) at SimpleFeedback (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243587:27) at div at div at TabComponent (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243891:25) at div at TabsComponent (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:243896:26) at ShortAnswer (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:244655:41) at AuthoringElementProvider (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:230393:3) at Provider_Provider (https://proton.oli.cmu.edu/js/oli_short_answer_authoring-739cd99f1f8f786457a0ed830beb2fea.js?vsn=d:219512:20)

**Comment by cjlim1092** [comment]
likely this is no longer a problem
