### ISSUE TITLE
Cannot open media manager to change existing image

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#3089]
On Tokamana, for a page with an image already on it, if I click the button to open the media manager the entire page content disappears and I see this in console:

```
react_devtools_backend.js:4026 TypeError: Cannot read properties of undefined (reading 'url')
    at MediaManager_MediaManager.renderMediaSelectionDetails (MediaManager.tsx:526:36)
    at MediaManager_MediaManager.render (MediaManager.tsx:738:19)
    at Te (react-dom.production.min.js:119:308)
    at Ch (react-dom.production.min.js:119:105)
    at Pj (react-dom.production.min.js:233:139)
    at di (react-dom.production.min.js:168:305)
    at Nj (react-dom.production.min.js:168:236)
    at sc (react-dom.production.min.js:168:96)
    at gf (react-dom.production.min.js:162:109)
    at react-dom.production.min.js:73:230
overrideMethod @ react_devtools_backend.js:4026
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(anonymous) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
Pa @ react-dom.production.min.js:157
enqueueSetState @ react-dom.production.min.js:218
v.setState @ react.production.min.js:19
(anonymous) @ MediaManager.tsx:177
Promise.then (async)
componentDidMount @ MediaManager.tsx:176
Bj @ react-dom.production.min.js:144
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(anonymous) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
vk.Events.current @ react-dom.production.min.js:240
Ki @ react-dom.production.min.js:44
ulemb_budgeting_and_tax_policy_ooge6:1 Uncaught (in promise) undefined
Promise.then (async)
execute @ ImageSettings.tsx:40
execute @ commandFactories.ts:31
onMouseDown @ CommandButton.tsx:21
vi @ react-dom.production.min.js:202
ui @ react-dom.production.min.js:32
xi @ react-dom.production.min.js:32
zg @ react-dom.production.min.js:55
rg @ react-dom.production.min.js:56
(anonymous) @ react-dom.production.min.js:66
(anonymous) @ react-dom.production.min.js:240
ti @ react-dom.production.min.js:30
hg @ react-dom.production.min.js:59
be @ react-dom.production.min.js:46
he @ react-dom.production.min.js:45
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
vk.Events.current @ react-dom.production.min.js:240
Ki @ react-dom.production.min.js:44
```

**Comment by marc-hughes** [comment]
Cause of the bug:

We make 2 network calls for media-items. One for a single item of the selected image (so we can get it's ID) and then another to get the full list of items to populate the list with.

There's a race condition between those. If the single-item one finishes first, you'll see this error.

You can replicate this locally by introducing a small delay when returning multiple items in media_library.ex around line 126

```
      _ ->
        case count_query |> Repo.one() do
          0 ->
            {:ok, {[], 0}}

          1 ->
            {:ok, {full_query |> Repo.all(), 1}}

          count ->
            :timer.sleep(3000)  
            {:ok, {full_query |> Repo.all(), count}}
        end
```
